f=open("1.txt","r")
data=f.read()
print("file content:",data)
f.close()

f=open("1.txt","r")
data=f.read(10)
print("First part:",data)
f.close()

f=open("1.txt","r")
line1=f.readline()
line2=f.readline()
line3=f.readline()
print("Line1:",line1)
print("Line2:",line2)
print("Line3:",line3)
f.close()

f=open("1.txt","r")
lines=f.readline()
print("List of lines:",lines)
print("Numbers of lines:",len(lines))
f.close()

f=open("1.txt","r")
lines=f.readlines()
print(lines[1].strip())
f.close()